/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Study04RouteImport } from './routes/study-04'
import { Route as Study03RouteImport } from './routes/study-03'
import { Route as Study02RouteImport } from './routes/study-02'
import { Route as Study01RouteImport } from './routes/study-01'
import { Route as IndexRouteImport } from './routes/index'

const Study04Route = Study04RouteImport.update({
  id: '/study-04',
  path: '/study-04',
  getParentRoute: () => rootRouteImport,
} as any)
const Study03Route = Study03RouteImport.update({
  id: '/study-03',
  path: '/study-03',
  getParentRoute: () => rootRouteImport,
} as any)
const Study02Route = Study02RouteImport.update({
  id: '/study-02',
  path: '/study-02',
  getParentRoute: () => rootRouteImport,
} as any)
const Study01Route = Study01RouteImport.update({
  id: '/study-01',
  path: '/study-01',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/study-01': typeof Study01Route
  '/study-02': typeof Study02Route
  '/study-03': typeof Study03Route
  '/study-04': typeof Study04Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/study-01': typeof Study01Route
  '/study-02': typeof Study02Route
  '/study-03': typeof Study03Route
  '/study-04': typeof Study04Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/study-01': typeof Study01Route
  '/study-02': typeof Study02Route
  '/study-03': typeof Study03Route
  '/study-04': typeof Study04Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/study-01' | '/study-02' | '/study-03' | '/study-04'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/study-01' | '/study-02' | '/study-03' | '/study-04'
  id: '__root__' | '/' | '/study-01' | '/study-02' | '/study-03' | '/study-04'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Study01Route: typeof Study01Route
  Study02Route: typeof Study02Route
  Study03Route: typeof Study03Route
  Study04Route: typeof Study04Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study-04': {
      id: '/study-04'
      path: '/study-04'
      fullPath: '/study-04'
      preLoaderRoute: typeof Study04RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-03': {
      id: '/study-03'
      path: '/study-03'
      fullPath: '/study-03'
      preLoaderRoute: typeof Study03RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-02': {
      id: '/study-02'
      path: '/study-02'
      fullPath: '/study-02'
      preLoaderRoute: typeof Study02RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-01': {
      id: '/study-01'
      path: '/study-01'
      fullPath: '/study-01'
      preLoaderRoute: typeof Study01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Study01Route: Study01Route,
  Study02Route: Study02Route,
  Study03Route: Study03Route,
  Study04Route: Study04Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
